displayName: Home Assistant Authentication Middleware
type: middleware
import: github.com/TritonNET/ha-auth-middleware
summary: Home Assistant Authentication Middleware

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  Headers:
    Foo: Bar